#!/bin/bash

cd src;

. .env

# we want to repopulate these, http first for certbot
rm .nginx/http*.conf
mv .tmp/http-*.conf .nginx/
docker-compose up nginx -d

# GENERATE CERTS
echo "Praying to the letsencrypt gods for my certs"
for A_NAME in $(echo $DIGITAL_OCEAN_A_RECORDS | tr ',' ' '); do
    export DOMAIN=$DIGITAL_OCEAN_DOMAIN
    if [ "$A_NAME" != "@" ]; then 
        export DOMAIN="$A_NAME.$DOMAIN"
    fi
    # TODO only proceed if certs don't already exist
    if ! sudo test -e ".certbot/certs/live/$DOMAIN"; then
        echo "Running cert bot for $DOMAIN"
        docker-compose up certbot
    fi
done

# SSL CONFIG
echo "Praying to the SSL gods for security"
# TODO Only do this if the file doesn't exist
if ! sudo test -e .certbot/certs/options-ssl-nginx.conf; then 
    sudo curl -L --create-dirs -o .certbot/certs/options-ssl-nginx.conf https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
fi 

# TODO Only do this if the file doesn't exist
if ! sudo test -e .certbot/certs/ssl-dhparams.pem; then 
    sudo openssl dhparam -out .certbot/certs/ssl-dhparams.pem 2048
fi

# now that we've got our certs, reload with https
mv .tmp/https-*.conf .nginx/
docker-compose exec nginx nginx -s reload

echo "Migrating data base and create super user"
docker-compose exec app "/bin/bash" -c "./manage.py migrate && ./manage.py createsuperuser --noinput" 
