# Generated by Django 3.1.14 on 2023-05-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_messagemodel_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
