# Generated by Django 3.1.14 on 2023-03-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botname', models.CharField(default=None, max_length=100)),
                ('primer', models.TextField()),
                ('openai_api_key', models.CharField(default='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', max_length=100)),
                ('openai_completion_model', models.CharField(default='text-davinci-003', max_length=100)),
                ('openai_embedding_model', models.CharField(default='text-embedding-ada-002', max_length=100)),
                ('openai_token_length', models.FloatField(default=3.5)),
                ('openai_temperature', models.FloatField(default=0.8)),
                ('openai_response_tokens', models.IntegerField(default=256)),
                ('openai_max_tokens', models.IntegerField(default=4000)),
            ],
        ),
    ]
