# Generated by Django 3.1.14 on 2023-04-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='end_point',
            field=models.CharField(default='http://localhost:8001/api/message/None', max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='openai_api_key',
            field=models.CharField(max_length=100),
        ),
    ]
