# Generated by Django 3.1.14 on 2023-05-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20230505_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='openai_api_key',
            field=models.CharField(default='sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', max_length=100),
        ),
    ]
