# Generated by Django 3.1.14 on 2023-05-09 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0004_auto_20230507_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='openai_completion_model',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='openai_embedding_model',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='openai_max_tokens',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='openai_response_tokens',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='openai_temperature',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='openai_token_length',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='primer',
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot', to=settings.AUTH_USER_MODEL, verbose_name='bot_user'),
        ),
        migrations.AddField(
            model_name='bot',
            name='config',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='end_point',
            field=models.CharField(default='http://bot:8001/api/message/[botname]/', max_length=255),
        ),
    ]
